#!/usr/bin/env python

import os
import sys
import csv
import argparse

dining = ()

catmap = {}   

parser = argparse.ArgumentParser(
    prog='amex2qif',
    description='''Convert American Express CSV export files to QIF format''',
    epilog='''If you provide a 'categories.py' file in the same directory
              as the amex2qif program, it will automatically be used. 
              The file should have two entries: 

                dining = (list of string names of restaurant names)

                catmap = {dictionary, key=string name of vendor, value=category (string)

                All vendors matching one of the dining items will be set to the category 'Dining'.
           ''')
parser.add_argument('csvfilename', type=str)

args = parser.parse_args()

edir = os.path.dirname(os.path.abspath(__file__))
if os.path.exists(os.path.join(edir, 'categories.py')):
   sys.path.append(edir)
   from categories import dining, catmap


with open(args.csvfilename, 'r') as csvfile:
   csvreader = csv.reader(csvfile, delimiter=',', quotechar='"')
   for i, row in enumerate(csvreader):
      if len(row) == 0:
         # Ignore blank lines
         continue
      if len(row) < 5:
         print >> sys.stderr, "Error in line %d: only %d field(s)!" % (i, len(row))
         continue

      if 0:
         date = row[0].split()[0]
         ref = None
         payee = row[2]
         customer = row[3].split()[0]
         amount = -float(row[7])
         memo = None
      else:
         date = row[0]
         ref = row[1].split()[1]
         amount = float(row[2])
         payee = row[3]
         memo = row[4]
         customer = None
         # customer = row[3].split()[0]

      category = ''

      for d in dining:
         if d in payee:
            category = 'Dining'

      for p,cat in catmap.items():
         if p in payee:
            category = cat

      if customer:
         category += "/%s" % customer

      if memo and ref:
         memo += " Ref: %s" % ref

      print "D%s" % date
      print "T%.2f" % amount
      print "P%s" % payee
      print "L%s" % category
      if memo:
         print "M%s" % memo
      print "^"
